import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import UserProvider from "@/provider/user-provider";
import { ThemeProvider } from "@/provider/theme-provider";
import Link from "next/link";
import Image from "next/image";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <UserProvider>
            {children}
            <footer className=" text-white py-12">
              <div className="container mx-auto px-4 sm:px-6 lg:px-8">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                  <div className="space-y-4">
                    <div className="flex flex-col justify-center items-center">
                      <Link href="/" className="flex items-center gap-2 group">
                        <Image src="/icon-logo.png" alt="HealthPlatform" width={60} height={44} />
                        <Image src="/text-logo.png" alt="HealthPlatform" width={200} height={24} />
                      </Link>
                      <p className="text-4xl font-extrabold text-blue-800">Doctors</p>
                    </div>
                    <p className="text-gray-400 text-sm leading-relaxed">
                      Connecting healthcare professionals to improve patient outcomes worldwide.
                    </p>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold mb-4">Product</h4>
                    <ul className="space-y-2 text-sm text-gray-400">
                      <li><Link href="#" className="hover:text-white transition-colors">Features</Link></li>
                      <li><Link href="#" className="hover:text-white transition-colors">Pricing</Link></li>
                      <li><Link href="#" className="hover:text-white transition-colors">Security</Link></li>
                    </ul>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold mb-4">Company</h4>
                    <ul className="space-y-2 text-sm text-gray-400">
                      <li><Link href="#" className="hover:text-white transition-colors">About</Link></li>
                      <li><Link href="#" className="hover:text-white transition-colors">Contact</Link></li>
                      <li><Link href="#" className="hover:text-white transition-colors">Careers</Link></li>
                    </ul>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold mb-4">Support</h4>
                    <ul className="space-y-2 text-sm text-gray-400">
                      <li><Link href="#" className="hover:text-white transition-colors">Help Center</Link></li>
                      <li><Link href="#" className="hover:text-white transition-colors">Documentation</Link></li>
                      <li><Link href="#" className="hover:text-white transition-colors">Privacy Policy</Link></li>
                    </ul>
                  </div>
                </div>
                
                <div className="border-t border-gray-800 mt-8 pt-8 text-center text-sm text-gray-400">
                  <p>&copy; 2024 DentalIcons. All rights reserved.</p>
                </div>
              </div>
            </footer>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
